version: '3'
services:
  php:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    container_name: php
    environment:
      XDEBUG_CONFIG: idekey=PHPSTORM
    volumes:
      - ./code:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/xdebug-php.ini
    depends_on:
      - mysql
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./code:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"