<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNerMMYx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__ . '/ContainerNerMMYx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNerMMYx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNerMMYx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNerMMYx\App_KernelDevDebugContainer([
    'container.build_hash' => 'NerMMYx',
    'container.build_id' => '3272a57c',
    'container.build_time' => 1584707138,
], __DIR__ . \DIRECTORY_SEPARATOR);
